# Generated by Django 4.0.5 on 2023-06-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirtiapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
