# Generated by Django 4.0.5 on 2023-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kirtiapp', '0002_delete_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=150)),
            ],
        ),
    ]
