# Generated by Django 4.0.5 on 2023-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirtiapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='viewed',
            name='description',
        ),
        migrations.RemoveField(
            model_name='viewed',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='viewed',
            name='ip',
        ),
        migrations.AddField(
            model_name='connection',
            name='device_type',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='latitude',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='location',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='longitude',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viewed',
            name='device_type',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='browser',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='email',
            field=models.EmailField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='ip',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='message',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='os',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='phone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='time',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='browser',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='os',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='time',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
